// Downloads the official game images listed in src/data/images.json, converts them to
// WebP without cropping, records their dimensions, and regenerates IMAGE_CREDITS.md.
//
//   npm run images            # fetch anything missing
//   npm run images -- --force # re-download and re-encode everything
//
// Only add images from official sources: developer/publisher sites and press kits,
// Steam, the Nintendo eShop, the App Store or Google Play.
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import sharp from 'sharp'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const manifestPath = path.join(root, 'src/data/images.json')
const outDir = path.join(root, 'public/images/games')
const force = process.argv.includes('--force')

// Landscape images are capped at 1280 px wide (cards and the review hero never show
// them larger). Portrait phone screenshots are capped at 1100 px tall.
const MAX_WIDTH = 1280
const MAX_PORTRAIT_HEIGHT = 1100
// Extra widths written next to each image for responsive srcset.
const LANDSCAPE_WIDTHS = [400, 560, 720, 960]
const PORTRAIT_WIDTHS = [140, 220, 320]

const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'))
fs.mkdirSync(outDir, { recursive: true })

for (const [slug, images] of Object.entries(manifest)) {
  for (const image of images) {
    const out = path.join(outDir, image.file)
    if (force || !fs.existsSync(out)) {
      const res = await fetch(image.source, { headers: { 'User-Agent': 'Mozilla/5.0 (cozycouplegames image fetch)' } })
      if (!res.ok) throw new Error(`${slug}: ${res.status} for ${image.source}`)
      const input = Buffer.from(await res.arrayBuffer())
      const meta = await sharp(input).metadata()
      const portrait = meta.height > meta.width
      await sharp(input)
        .resize(
          portrait
            ? { height: MAX_PORTRAIT_HEIGHT, withoutEnlargement: true }
            : { width: MAX_WIDTH, withoutEnlargement: true },
        ) // aspect ratio is always preserved; nothing is cropped
        .webp({ quality: 80, effort: 6 })
        .toFile(out)
      console.log(`✓ ${image.file}  (${meta.width}×${meta.height} ${meta.format} → webp)`)
    }
    const { width, height } = await sharp(out).metadata()
    image.width = width
    image.height = height
    image.bytes = fs.statSync(out).size

    // Smaller copies for srcset, so phones and cards never download the full file.
    const widths = (height > width ? PORTRAIT_WIDTHS : LANDSCAPE_WIDTHS).filter((w) => w < width)
    for (const w of widths) {
      const variant = path.join(outDir, image.file.replace(/\.webp$/, `-${w}.webp`))
      if (force || !fs.existsSync(variant)) {
        await sharp(out).resize({ width: w }).webp({ quality: 78, effort: 6 }).toFile(variant)
      }
    }
    image.widths = [...widths, width]

    // Social preview (og:image) for landscape images. JPEG because not every platform
    // accepts WebP previews; 16:9 is kept as-is rather than cropped to 1.91:1.
    if (width > height && images.indexOf(image) === 0) {
      const og = path.join(outDir, image.file.replace(/\.webp$/, '-og.jpg'))
      if (force || !fs.existsSync(og)) {
        await sharp(out).resize({ width: 1200 }).jpeg({ quality: 82, mozjpeg: true }).toFile(og)
      }
      image.og = path.basename(og)
    }
  }
}

fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n')

const rows = Object.entries(manifest).flatMap(([slug, images]) =>
  images.map(
    (i) =>
      `| \`${i.file}\` | ${slug} | ${i.copyright} | [${i.store}](${i.page}) | [original](${i.source}) | ${i.width}×${i.height}, ${Math.round(i.bytes / 1024)} KB |`,
  ),
)
fs.writeFileSync(
  path.join(root, 'IMAGE_CREDITS.md'),
  `# Image credits

All game images on Cozy Couple Games are official screenshots or promotional art published by
the game's developer or publisher on an official storefront. They are used for editorial review
and remain the property of their respective owners. Files live in \`public/images/games/\`; the
source of truth is \`src/data/images.json\`, and this file is regenerated by
\`npm run images\`.

| File | Game | © | Official page | Source file | Size |
| --- | --- | --- | --- | --- | --- |
${rows.join('\n')}
`,
)
console.log(`Wrote dimensions to src/data/images.json and regenerated IMAGE_CREDITS.md (${rows.length} images).`)
